// <auto-generated />
using System;
using EconomIA.Adapters.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EconomIA.Adapters.Persistence.Migrations
{
    [DbContext(typeof(EconomIACommandDbContext))]
    partial class EconomIACommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EconomIA.Domain.Ata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnoAta")
                        .HasColumnType("integer")
                        .HasColumnName("ano_ata");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<bool>("Cancelado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelado");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_assinatura");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataAtualizacaoGlobal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_global");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cancelamento");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<DateTime?>("DataPublicacaoPncp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao_pncp");

                    b.Property<long>("IdentificadorDoOrgao")
                        .HasColumnType("bigint")
                        .HasColumnName("identificador_do_orgao");

                    b.Property<string>("NumeroAtaRegistroPreco")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_ata_registro_preco");

                    b.Property<string>("NumeroControlePncpAta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp_ata");

                    b.Property<string>("NumeroControlePncpCompra")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp_compra");

                    b.Property<string>("ObjetoContratacao")
                        .HasColumnType("text")
                        .HasColumnName("objeto_contratacao");

                    b.Property<string>("Usuario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario");

                    b.Property<DateTime?>("VigenciaFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_fim");

                    b.Property<DateTime?>("VigenciaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id")
                        .HasName("pk_ata");

                    b.HasIndex("AnoAta")
                        .HasDatabaseName("ix_ata_AnoAta");

                    b.HasIndex("IdentificadorDoOrgao")
                        .HasDatabaseName("ix_ata_IdentificadorDoOrgao");

                    b.HasIndex("NumeroControlePncpAta")
                        .IsUnique()
                        .HasDatabaseName("un_ata_NumeroControlePncpAta");

                    b.HasIndex("NumeroControlePncpCompra")
                        .HasDatabaseName("ix_ata_NumeroControlePncpCompra");

                    b.ToTable("ata", (string)null);
                });

            modelBuilder.Entity("EconomIA.Domain.Compra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AmparoLegalNome")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("amparo_legal_nome");

                    b.Property<int>("AnoCompra")
                        .HasColumnType("integer")
                        .HasColumnName("ano_compra");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAberturaProposta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_abertura_proposta");

                    b.Property<DateTime?>("DataAtualizacaoGlobal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_global");

                    b.Property<DateTime?>("DataEncerramentoProposta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_encerramento_proposta");

                    b.Property<DateTime?>("DataInclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao");

                    b.Property<long>("IdentificadorDoOrgao")
                        .HasColumnType("bigint")
                        .HasColumnName("identificador_do_orgao");

                    b.Property<bool>("ItensCarregados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("itens_carregados");

                    b.Property<string>("LinkPncp")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_pncp");

                    b.Property<int>("ModalidadeIdentificador")
                        .HasColumnType("integer")
                        .HasColumnName("modalidade_identificador");

                    b.Property<string>("ModalidadeNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("modalidade_nome");

                    b.Property<string>("ModoDisputaNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("modo_disputa_nome");

                    b.Property<string>("NumeroControlePncp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp");

                    b.Property<string>("ObjetoCompra")
                        .HasColumnType("text")
                        .HasColumnName("objeto_compra");

                    b.Property<int>("SequencialCompra")
                        .HasColumnType("integer")
                        .HasColumnName("sequencial_compra");

                    b.Property<string>("SituacaoCompraNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("situacao_compra_nome");

                    b.Property<decimal?>("ValorTotalEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total_estimado");

                    b.Property<decimal?>("ValorTotalHomologado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total_homologado");

                    b.HasKey("Id")
                        .HasName("pk_compra");

                    b.HasIndex("IdentificadorDoOrgao", "AnoCompra", "SequencialCompra")
                        .IsUnique()
                        .HasDatabaseName("un_compra_IdentificadorDoOrgao_AnoCompra_SequencialCompra");

                    b.ToTable("compra", (string)null);
                });

            modelBuilder.Entity("EconomIA.Domain.Contrato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AnoContrato")
                        .HasColumnType("integer")
                        .HasColumnName("ano_contrato");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int?>("CategoriaProcessoId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_processo_id");

                    b.Property<string>("CategoriaProcessoNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("categoria_processo_nome");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAssinatura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_assinatura");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataAtualizacaoGlobal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_global");

                    b.Property<DateTime?>("DataPublicacaoPncp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_publicacao_pncp");

                    b.Property<DateTime?>("DataVigenciaFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vigencia_fim");

                    b.Property<DateTime?>("DataVigenciaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vigencia_inicio");

                    b.Property<long>("IdentificadorDoOrgao")
                        .HasColumnType("bigint")
                        .HasColumnName("identificador_do_orgao");

                    b.Property<string>("InformacaoComplementar")
                        .HasColumnType("text")
                        .HasColumnName("informacao_complementar");

                    b.Property<string>("NiFornecedor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ni_fornecedor");

                    b.Property<string>("NomeRazaoSocialFornecedor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome_razao_social_fornecedor");

                    b.Property<string>("NumeroContratoEmpenho")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("numero_contrato_empenho");

                    b.Property<string>("NumeroControlePncp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp");

                    b.Property<string>("NumeroControlePncpCompra")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_controle_pncp_compra");

                    b.Property<int?>("NumeroParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcelas");

                    b.Property<string>("ObjetoContrato")
                        .HasColumnType("text")
                        .HasColumnName("objeto_contrato");

                    b.Property<string>("Processo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("processo");

                    b.Property<bool>("Receita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("receita");

                    b.Property<int>("SequencialContrato")
                        .HasColumnType("integer")
                        .HasColumnName("sequencial_contrato");

                    b.Property<int?>("TipoContratoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_contrato_id");

                    b.Property<string>("TipoContratoNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tipo_contrato_nome");

                    b.Property<string>("TipoPessoa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo_pessoa");

                    b.Property<string>("UsuarioNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario_nome");

                    b.Property<decimal?>("ValorAcumulado")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_acumulado");

                    b.Property<decimal?>("ValorGlobal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_global");

                    b.Property<decimal?>("ValorInicial")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_inicial");

                    b.Property<decimal?>("ValorParcela")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_parcela");

                    b.HasKey("Id")
                        .HasName("pk_contrato");

                    b.HasIndex("AnoContrato")
                        .HasDatabaseName("ix_contrato_AnoContrato");

                    b.HasIndex("IdentificadorDoOrgao")
                        .HasDatabaseName("ix_contrato_IdentificadorDoOrgao");

                    b.HasIndex("NiFornecedor")
                        .HasDatabaseName("ix_contrato_NiFornecedor");

                    b.HasIndex("NumeroControlePncp")
                        .IsUnique()
                        .HasDatabaseName("un_contrato_NumeroControlePncp");

                    b.ToTable("contrato", (string)null);
                });

            modelBuilder.Entity("EconomIA.Domain.ItemDaCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriterioJulgamentoNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("criterio_julgamento_nome");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long>("IdentificadorDaCompra")
                        .HasColumnType("bigint")
                        .HasColumnName("identificador_da_compra");

                    b.Property<int>("NumeroItem")
                        .HasColumnType("integer")
                        .HasColumnName("numero_item");

                    b.Property<decimal?>("Quantidade")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade");

                    b.Property<string>("SituacaoCompraItemNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("situacao_compra_item_nome");

                    b.Property<bool>("TemResultado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tem_resultado");

                    b.Property<string>("UnidadeMedida")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unidade_medida");

                    b.Property<decimal?>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.Property<decimal?>("ValorUnitarioEstimado")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_unitario_estimado");

                    b.HasKey("Id")
                        .HasName("pk_item_da_compra");

                    b.HasIndex("IdentificadorDaCompra", "NumeroItem")
                        .IsUnique()
                        .HasDatabaseName("un_item_da_compra_IdentificadorDaCompra_NumeroItem");

                    b.ToTable("item_da_compra", (string)null);
                });

            modelBuilder.Entity("EconomIA.Domain.Orgao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoNaturezaJuridica")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_natureza_juridica");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAtualizacaoPncp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_pncp");

                    b.Property<DateTime?>("DataInclusaoPncp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao_pncp");

                    b.Property<DateTime?>("DataSituacaoCadastral")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_situacao_cadastral");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_validacao");

                    b.Property<string>("DescricaoNaturezaJuridica")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao_natureza_juridica");

                    b.Property<string>("EsferaId")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("esfera_id");

                    b.Property<string>("JustificativaAtualizacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justificativa_atualizacao");

                    b.Property<string>("MotivoSituacaoCadastral")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_situacao_cadastral");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("PoderId")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("poder_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("razao_social");

                    b.Property<string>("SituacaoCadastral")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("situacao_cadastral");

                    b.Property<bool>("StatusAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status_ativo");

                    b.Property<bool>("Validado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("validado");

                    b.HasKey("Id")
                        .HasName("pk_orgao");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("un_orgao_Cnpj");

                    b.ToTable("orgao", (string)null);
                });

            modelBuilder.Entity("EconomIA.Domain.ResultadoDoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime?>("DataResultado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_resultado");

                    b.Property<long>("IdentificadorDoItemDaCompra")
                        .HasColumnType("bigint")
                        .HasColumnName("identificador_do_item_da_compra");

                    b.Property<string>("NiFornecedor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ni_fornecedor");

                    b.Property<string>("NomeRazaoSocialFornecedor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome_razao_social_fornecedor");

                    b.Property<decimal?>("QuantidadeHomologada")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantidade_homologada");

                    b.Property<string>("SituacaoCompraItemResultadoNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("situacao_compra_item_resultado_nome");

                    b.Property<decimal?>("ValorTotalHomologado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total_homologado");

                    b.Property<decimal?>("ValorUnitarioHomologado")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_unitario_homologado");

                    b.HasKey("Id")
                        .HasName("pk_resultado_do_item");

                    b.HasIndex("IdentificadorDoItemDaCompra", "NiFornecedor")
                        .IsUnique()
                        .HasDatabaseName("un_resultado_do_item_IdentificadorDoItemDaCompra_NiFornecedor");

                    b.ToTable("resultado_do_item", (string)null);
                });

            modelBuilder.Entity("EconomIA.Domain.Unidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("identificador");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CodigoUnidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_unidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAtualizacaoPncp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao_pncp");

                    b.Property<DateTime?>("DataInclusaoPncp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inclusao_pncp");

                    b.Property<long>("IdentificadorDoOrgao")
                        .HasColumnType("bigint")
                        .HasColumnName("identificador_do_orgao");

                    b.Property<string>("JustificativaAtualizacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("justificativa_atualizacao");

                    b.Property<string>("MunicipioCodigoIbge")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("municipio_codigo_ibge");

                    b.Property<string>("MunicipioNome")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("municipio_nome");

                    b.Property<string>("NomeUnidade")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome_unidade");

                    b.Property<bool>("StatusAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status_ativo");

                    b.Property<string>("UfNome")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uf_nome");

                    b.Property<string>("UfSigla")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf_sigla");

                    b.HasKey("Id")
                        .HasName("pk_unidade");

                    b.HasIndex("MunicipioCodigoIbge")
                        .HasDatabaseName("ix_unidade_MunicipioCodigoIbge");

                    b.HasIndex("UfSigla")
                        .HasDatabaseName("ix_unidade_UfSigla");

                    b.HasIndex("IdentificadorDoOrgao", "CodigoUnidade")
                        .IsUnique()
                        .HasDatabaseName("un_unidade_IdentificadorDoOrgao_CodigoUnidade");

                    b.ToTable("unidade", (string)null);
                });

            modelBuilder.Entity("EconomIA.Domain.Ata", b =>
                {
                    b.HasOne("EconomIA.Domain.Orgao", "Orgao")
                        .WithMany()
                        .HasForeignKey("IdentificadorDoOrgao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ata_IdentificadorDoOrgao_to_orgao_Id");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("EconomIA.Domain.Compra", b =>
                {
                    b.HasOne("EconomIA.Domain.Orgao", "Orgao")
                        .WithMany()
                        .HasForeignKey("IdentificadorDoOrgao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compra_IdentificadorDoOrgao_to_orgao_Id");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("EconomIA.Domain.Contrato", b =>
                {
                    b.HasOne("EconomIA.Domain.Orgao", "Orgao")
                        .WithMany()
                        .HasForeignKey("IdentificadorDoOrgao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contrato_IdentificadorDoOrgao_to_orgao_Id");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("EconomIA.Domain.ItemDaCompra", b =>
                {
                    b.HasOne("EconomIA.Domain.Compra", "Compra")
                        .WithMany("ItensDaCompra")
                        .HasForeignKey("IdentificadorDaCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_da_compra_IdentificadorDaCompra_to_compra_Id");

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("EconomIA.Domain.ResultadoDoItem", b =>
                {
                    b.HasOne("EconomIA.Domain.ItemDaCompra", "ItemDaCompra")
                        .WithMany("Resultados")
                        .HasForeignKey("IdentificadorDoItemDaCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resultado_do_item_IdentificadorDoItemDaCompra_to_item_da_compra_Id");

                    b.Navigation("ItemDaCompra");
                });

            modelBuilder.Entity("EconomIA.Domain.Unidade", b =>
                {
                    b.HasOne("EconomIA.Domain.Orgao", "Orgao")
                        .WithMany("Unidades")
                        .HasForeignKey("IdentificadorDoOrgao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_unidade_IdentificadorDoOrgao_to_orgao_Id");

                    b.Navigation("Orgao");
                });

            modelBuilder.Entity("EconomIA.Domain.Compra", b =>
                {
                    b.Navigation("ItensDaCompra");
                });

            modelBuilder.Entity("EconomIA.Domain.ItemDaCompra", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("EconomIA.Domain.Orgao", b =>
                {
                    b.Navigation("Unidades");
                });
#pragma warning restore 612, 618
        }
    }
}
